### ISSUE TITLE
Problem with user defined fields on Phpbb3.2

### ISSUE THREAD

**Issue by thefactor82** [oxpus/Download-32-Extension#1]
Hi,
I've installed succesfully the Oxpus Download extension 7.2.11 on my fresh phpbb 3.2 forum.
When I try to add a user defined field, I get this error:

Fatal error: Call to a member function add() on null in .....phpBB3\ext\oxpus\dlext\acp\main_module.php on line 776

Could you please check it?

**Comment by oxpus** [comment]
ACP module updated.
Replace them to fix the error.

**Comment by thefactor82** [comment]
Thanks for this fast answer!
I replace the ACP modules and the field get now created correctly via ACP.
But when trying to insert something in this field, I get SQL error:
(the field I have created is a TEXT field, named "tredi")

SQL ERROR [ mysql4 ]

Unknown column 'pf_tredi' in 'field list' [1054]

SQL

UPDATE phpbb3g_dl_fields_data SET pf_tredi = 'adasdasd' WHERE df_id = 2

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysql.php
LINE: 191
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysql->sql_query()

FILE: [ROOT]/ext/oxpus/dlext/includes/helpers/dl_fields.php
LINE: 339
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/ext/oxpus/dlext/includes/modules/dl_upload.php
LINE: 400
CALL: oxpus\dlext\includes\helpers\custom_profile->update_profile_field_data()

FILE: [ROOT]/ext/oxpus/dlext/controller/main.php
LINE: 1003
CALL: include('[ROOT]/ext/oxpus/dlext/includes/modules/dl_upload.php')

FILE: (not given by php)
LINE: (not given by php)
CALL: oxpus\dlext\controller\main->handle()

FILE: [ROOT]/vendor/symfony/http-kernel/HttpKernel.php
LINE: 144
CALL: call_user_func_array()

FILE: [ROOT]/vendor/symfony/http-kernel/HttpKernel.php
LINE: 64
CALL: Symfony\Component\HttpKernel\HttpKernel->handleRaw()

FILE: [ROOT]/app.php
LINE: 35
CALL: Symfony\Component\HttpKernel\HttpKernel->handle()

**Comment by oxpus** [comment]
Hm, I've done the same now and I don't gets an error.
Please drop this field and create it again.
The field should be added as new column in the table "phpbb3g_dl_fields_data".
It's the same procedure as the forum creates custom profile files.

**Comment by thefactor82** [comment]
Tried again,  without success...In my environment, although the field creation goes well on the ACP, the column is NOT added to the table phpbb3g_dl_fields_data, generating sql error when I try to use it...What I can check now?Thanks in advance




----Messaggio originale----

Da: "Karsten Ude" <notifications@github.com>

Data: 29-ago-2017 18.30

A: "oxpus/Download-32-Extension"<Download-32-Extension@noreply.github.com>

Cc: "thefactor82"<mam1982@virgilio.it>, "Author"<author@noreply.github.com>

Ogg: Re: [oxpus/Download-32-Extension] Problem with user defined fields on Phpbb3.2 (#1)




Hm, I've done the same now and I don't gets an error.

Please drop this field and create it again.

The field should be added as new column in the table "phpbb3g_dl_fields_data".

It's the same procedure as the forum creates custom profile files.

**Comment by oxpus** [comment]
Can you please try another field types like numbers or option fields?

**Comment by thefactor82** [comment]
Tried one minute ago... No way... :-(Inside phpbb3g_dl_fields the field get created, but inside phpbb3g_dl_fields_data no columns are added...




----Messaggio originale----

Da: "Karsten Ude" <notifications@github.com>

Data: 30-ago-2017 20.54

A: "oxpus/Download-32-Extension"<Download-32-Extension@noreply.github.com>

Cc: "thefactor82"<mam1982@virgilio.it>, "Author"<author@noreply.github.com>

Ogg: Re: [oxpus/Download-32-Extension] Problem with user defined fields on Phpbb3.2 (#1)




Can you please try another field types like numbers or option fields?

**Comment by oxpus** [comment]
I think you have a problem with the database setting.
Creating new colums on a table should work per default.

Please retry after changing the mysql-driver from "mysql" to "mysqli" in your config.php.
And drop the board cache after changing this file to avoid other errors, too.

**Comment by thefactor82** [comment]
Tryed with your suggestion... Not working...:-(Can I help you to help me sending you come configuration files, screenshots, or something similar?Thanks for you help




----Messaggio originale----

Da: "Karsten Ude" <notifications@github.com>

Data: 1-set-2017 12.20

A: "oxpus/Download-32-Extension"<Download-32-Extension@noreply.github.com>

Cc: "thefactor82"<mam1982@virgilio.it>, "Author"<author@noreply.github.com>

Ogg: Re: [oxpus/Download-32-Extension] Problem with user defined fields on Phpbb3.2 (#1)




I think you have a problem with the database setting.

Creating new colums on a table should work per default.

Please retry after changing the mysql-driver from "mysql" to "mysqli" in your config.php.

And drop the board cache after changing this file to avoid other errors, too.

**Comment by oxpus** [comment]
Yes, if this can helps...

**Comment by thefactor82** [comment]
Actually, I have simply added manually the column named as the extension wants via phpmyadmin, and the custom field works properly.So maybe it is something related to my environment and from the moment that I need only one custom field to be added, I don't want to bother you with this.Actually my environment is in local via XAMPP. I'm planning to move this environment on my domain in the next two/three months, so then I will see if this problem is gone.
However, I have a question for you...It is possible to make BBCODES rendered inside a TEXT custom field? 




----Messaggio originale----

Da: "Karsten Ude" <notifications@github.com>

Data: 1-set-2017 12.42

A: "oxpus/Download-32-Extension"<Download-32-Extension@noreply.github.com>

Cc: "thefactor82"<mam1982@virgilio.it>, "Author"<author@noreply.github.com>

Ogg: Re: [oxpus/Download-32-Extension] Problem with user defined fields on Phpbb3.2 (#1)




Yes, if this can helps...

**Comment by oxpus** [comment]
Okay, we will see, if the online enviroment will work with/out errors.

And sorry, no. BBCodes needs at least 2-3 extra fields in the table to provide this functions in custom fields, too. The steering at this point is very difficult, so I've not implement bbcodes at this point.

**Comment by thefactor82** [comment]
Oh, that's a pity... :-(But I understand that this type of implementation could be very difficult...I hope that maybe one day... ;-)Thanks for your help, have a nice day!



----Messaggio originale----

Da: "Karsten Ude" <notifications@github.com>

Data: 1-set-2017 15.58

A: "oxpus/Download-32-Extension"<Download-32-Extension@noreply.github.com>

Cc: "thefactor82"<mam1982@virgilio.it>, "Author"<author@noreply.github.com>

Ogg: Re: [oxpus/Download-32-Extension] Problem with user defined fields on Phpbb3.2 (#1)




Okay, we will see, if the online enviroment will work with/out errors.

And sorry, no. BBCodes needs at least 2-3 extra fields in the table to provide this functions in custom fields, too. The steering at this point is very difficult, so I've not implement bbcodes at this point.

**Comment by oxpus** [comment]
Okay, thx and hopefull the installation online will work.
For now I close this issue.
Please open a new one on futher problems.
