### ISSUE TITLE
news

### ISSUE THREAD

**Issue by eunaumtenhoid** [oxpus/Download-32-Extension#10]
mannnnnnnnnnnn!!!!!
Thank you so much for this amazing version!

**some details I want to report to you:**
the profile shows the numbers of the add downloads by the user and a link to show them (all right), but on the search page it does not show the correct value, if you look at my images below the profile shows 4 add downloads and the search shows 5

![number dl](https://user-images.githubusercontent.com/22734333/82151774-b2e00000-9833-11ea-9b03-a326f8cbd11b.jpg)

![number dl pesquisa](https://user-images.githubusercontent.com/22734333/82151786-c68b6680-9833-11ea-9410-d213d00b57a1.jpg)

in the title of new downloads the language in them is not configured:
![no idioma](https://user-images.githubusercontent.com/22734333/82151846-05b9b780-9834-11ea-9226-e32d8b2d62bd.jpg)
this occurs on all pages that show the icon again:
![new 2](https://user-images.githubusercontent.com/22734333/82152065-3fd78900-9835-11ea-9b84-b33d67e6e34b.jpg)

**now some ideas to be even more fantastic in the updates you made:**
on the add downloads page by the user you can add the new or edited downlod icons as with all other pages and the title of this page which is currently "Downloads search results" could be something like downloads add by "USER NAME" ( with the color of the group and of course)

![new](https://user-images.githubusercontent.com/22734333/82152024-0d2d9080-9835-11ea-8fb5-6df3b6b73aa2.jpg)

in the quick links you could have a link there for the downloads added by the user something like >> view my downloads, this idea is just to make it easier to have q enter your profile to see, but in case it is not convenient ok too!

on acp in the new download option laste could have an option of only new download
![last](https://user-images.githubusercontent.com/22734333/82152147-bffdee80-9835-11ea-99e0-7b10a8cdc366.jpg)

on the download page it would be good to identify add the name of those who add the download and the date:
![add nome upload](https://user-images.githubusercontent.com/22734333/82152237-44507180-9836-11ea-85f4-a60743fe6a86.jpg)

the thumb we added in the download on the edit page, could appear in front of the download titles on the download body page, and can be turned off via acp.

DO YOU have an idea or the possibility of putting a like / deslike system for downloads? showing the total number of who thanked and the nicknames

curiosity >> because the route of its extension is not downloads >>mysite/testes/phpBB33/downloads/details?df_id=4 just to know out of curiosity

no more thanks again for this fantastic update

**Comment by oxpus** [comment]
>The search result is fixed now. The results contains downloads which are changed by the user.

>The missing language string was added.

>The add user with time was added on search results and in the categories

>The quick links menu includes now "My downloads"

>The lastest downloads contains alltimes new and updates downloads. There will be no option only for new downloads.

>To rearrange the thumbnails feel free to change the template yourself.

>No, there will not be a like/dislike function for downloads. This is an extension not a social media block.

curiosity >> because the route of its extension is not downloads
> This route is just wrong. The extension is hosted under dlext, not under downloads.
