### ISSUE TITLE
error deleted user

### ISSUE THREAD

**Issue by eunaumtenhoid** [oxpus/Download-32-Extension#11]
all the errors I saw were fixed, but this one appeared, I have 11 files:
![VISITANTE 3](https://user-images.githubusercontent.com/22734333/82165544-ce76f500-988b-11ea-87dd-05f91866dfb3.jpg)

but in the download list it only shows 10:
![VISITANTE 2](https://user-images.githubusercontent.com/22734333/82165562-e189c500-988b-11ea-8164-8498d5a89e19.jpg)

but in the MCP it shows the 11:
![VISITANTE](https://user-images.githubusercontent.com/22734333/82165571-ed758700-988b-11ea-9578-1db3f6174a9f.jpg)

I did a test deleting a user to see if the download was deleted, because I would not like the download to be deleted if a user is deleted

before it appeared on the list, even without a user in the last update

**Comment by oxpus** [comment]
Fixed now.

**Comment by oxpus** [comment]
BTW: To delete a user will keep all downloads which are added by this user. Only the favorites and traffic settings will be deleted.
