### ISSUE TITLE
fatal error on version 8.1.1 and phpBB3.3

### ISSUE THREAD

**Issue by Sajaki** [oxpus/Download-32-Extension#14]
hello, 

Since upgrading to phpBB 3.3 and Download extension 8.1.1, I have the following fatal error on my site when going to url https://www.avathar.be/forum/app.php/dlext

`Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Yaml\Parser::parseFile() in /customers/0/c/8/avathar.be/httpd.www/forum/vendor/symfony/routing/Loader/YamlFileLoader.php:67 Stack trace: #0 /customers/0/c/8/avathar.be/httpd.www/forum/vendor/symfony/config/Loader/DelegatingLoader.php(40): Symfony\Component\Routing\Loader\YamlFileLoader->load('config/producti...', 'yaml') #1 /customers/0/c/8/avathar.be/httpd.www/forum/phpbb/routing/router.php(116): Symfony\Component\Config\Loader\DelegatingLoader->load('config/producti...', 'yaml') #2 /customers/0/c/8/avathar.be/httpd.www/forum/phpbb/routing/router.php(206): phpbb\routing\router->get_routes() #3 /customers/0/c/8/avathar.be/httpd.www/forum/phpbb/routing/router.php(191): phpbb\routing\router->create_dumped_url_matcher() #4 /customers/0/c/8/avathar.be/httpd.www/forum/phpbb/routing/router.php(176): phpbb\routing\router->get_matcher() #5 /customers/0/c/8/avathar.be/httpd.www/forum/vendor/symfony/http-kernel/EventListener/RouterListener.php(115): phpbb\routi in /customers/0/c/8/avathar.be/httpd.www/forum/vendor/symfony/routing/Loader/YamlFileLoader.php on line 67`

Could you help please ?

**Comment by oxpus** [comment]
I think this is not an error by the extension but maybe the forum cache is broken or your PHP settings should be incompatible.

Which PHP version do you use?
And do you have already dropped the forum cache?

I uses multiple phpBB 3.3.0 with the download extension without any errors and I use a phpBB 3.3.x for my developments.

And btw:
`.../app.php/dlext` is not correct and not defined anymore in the extension.
Use `.../app.php/dlext/index` instead to open the download index.
But this URL produces the same errors in your forum...

**Comment by Sajaki** [comment]
i found the reason, it was an extension conflict. I disabled the faulty ext and downloads are working again.

**Comment by oxpus** [comment]
A conflict?
Which extension is faulty?

**Comment by Sajaki** [comment]
It was Paybas/Quicklogin. will do code analyse later.

**Comment by oxpus** [comment]
Examine the service.yml of this extension and add the missing '
That's all...

**Comment by Sajaki** [comment]
it's now fixed in https://github.com/Sajaki/QuickLogin

**Comment by oxpus** [comment]
Awesome.
