### ISSUE TITLE
Probleme with downloads

### ISSUE THREAD

**Issue by jon7dra** [oxpus/Download-32-Extension#17]
**_Hello,_**

First , i want to thank you for your extension, who is really great.

I have installed Oxpus Download on my test forum (https://diagrepaauto.fr/theme-test/) before to install it on my final forum .

_Here is my problem:_

- I can upload files directly thru the extension without problem, the download button is ok but when i click on it, the download, don't start.

- After that , i tried to upload a file in a readable folder of my forum , and generat a direct link download. Download button is ok but when i click on it, the download don't start.
To know: i tried my link by putting it directly in the search barre of my web browser and the link work good. I checked the permissions of the extension , groups, and forum , all is ok.

Can you help me to solve this please.
If needed i can create an account  for checking the configuration.

Thanks by advance.
Best regard.

Jon from Diag & Répa Auto team

**Comment by oxpus** [comment]
Please post the versions of your forum, the extension and PHP.

And when you click on the download button: Will the button be hidden and after this the download will just starts?

**Comment by jon7dra** [comment]
Thanks for your reply. 

PhpBB version is 3.3.0
The extension version is 8.1.6
Php version is 7.4.12

When i click on the download button, it's not hide, the page seem reload , and the download doesn't start.


Thanks for your help.
Best regard

**Comment by oxpus** [comment]
On click the download button it should be hidden and after this the download starts.
So there's something wrong with your setting.
Please purge the forum and browser caches and retry.

**Comment by jon7dra** [comment]
Thanks,

I tried to do what you said but it always the same.

**Comment by oxpus** [comment]
Another try:
You are using another style as prosilver, as I see is the name "basic_red".
The extension provides only files for prosilver.
Maybe it can help to create a copy of the folder /ext/oxpus/dlext/styles/**prosilver**/ to your style name /ext/oxpus/dlext/styles/**basic_red**.

**Comment by jon7dra** [comment]
Thanks,

I try it:
`cp -Rv basic_red/ /mnt/forum/public_html/theme_test/ext/oxpus/dlext/styles/`

**Comment by oxpus** [comment]
And the result?

**Comment by jon7dra** [comment]
The copy just finished , i cleared the cache of the forum and of my web browser and its always the same result.

**Comment by jon7dra** [comment]
I Tried with prosilver and it's the same result

**Comment by oxpus** [comment]
Hm, please open your download extension and take a look on the sourcecode.
You should find the folowing entries in this:
`<link href="./../../ext/oxpus/dlext/styles/prosilver/theme/dl_ext.css?assets_version=139" rel="stylesheet" media="screen" />`
and
`<script src="./../../ext/oxpus/dlext/assets/javascript/dl_footer.js?assets_version=139"></script>`
`<script src="./../../ext/oxpus/dlext/assets/javascript/ajax_dl.js?assets_version=139"></script>`
If these entries are missing the download button will not work properly.

When these entries are missing, you can try to disable all other extensions and enable them one by one for testing the download button.
There may exist an incompatible javascript function used by an other extension to block the download button.

**Comment by jon7dra** [comment]
You have find the problem, it's tapatalk who block the downloads.
I have inactivated tapatalk and all work good.

Do you know if there is a solution to use Oxpus and Tapatalk?

**Comment by oxpus** [comment]
No, Tapatalk is very buggy so I'll not support this extension.

Finally this issue isn't a bug of the download extension while Tapatalk blocks common javascript functions.
So I'll close here.

**Comment by jon7dra** [comment]
Yes , it wasn't a bug . thanks a lot for your help.

Best regard.
Jon.
