### ISSUE TITLE
Images not showing in Download details

### ISSUE THREAD

**Issue by thefactor82** [oxpus/Download-32-Extension#2]
Hi,
I've installed the Download extension 7.2.13 on a Phpbb 3.2.2 forum
When I upload a fine with an image as preview, the upload works correctly. The file is uploaded, and also the image (I can see it inside thumbs folder).
However on the donwload details page, the image is not showing (it shows a broken image link) and if I click on the link, I receive this message: Image cannot be loaded. Make sure the path is correct and image exist.

If I download the image from the thumbs folder, the image is working correctly.

**Comment by oxpus** [comment]
Please check the folder permissions for the thumbnails and try to open it via a direct link.

**Comment by LoScassatore** [comment]
Hi,
I am a collaborator of thefactor82
Checking the folder permissions, i noticed that a .htaccess file was present in the forumRoot/store/ directory.

`<Files *>
	Order Deny,Allow
	Allow from localhost 127.0.0.1 https://www.aliasrevoltmaster.com/forum
	Require ip 127.0.0.1
</Files>`

With this file, the store dir and all it's subirectories were not accessible via url, an error 500 was returned instead.

According to the document below
https://httpd.apache.org/docs/current/upgrading.html

**Comment by oxpus** [comment]
This is not the original .htaccess from the phpbb package. The original one contents only
`<Files *>
	Order Allow,Deny
	Deny from All
</Files>`
