### ISSUE TITLE
Change code {{ MINI_IMG }}

### ISSUE THREAD

**Issue by OfficialMT22** [oxpus/Download-32-Extension#26]
https://ibb.co/3Czv9rx

I would like to change the image that shows downloads are new (SEE IMAGE ABOVE)

only thing i can find in the script is in the (styles/template/vew_dl_body.html)

<h2 class="dl-left">{{ MINI_IMG }} {{ DESCRIPTION }} {{ HACK_VERSION }} </h2>

if i delete this ({{ MINI_IMG }}) - then the image goes away but i would like to change it from fa-comment-o to something else please help!

**Comment by oxpus** [comment]
In the current version, the definition for this icon can be changed in the file /ext/oxpus/dlext/controller/classes/dlext_status.php.

However, the extension is currently being in progress so these icons can later be changed directly in the template files.

**Comment by OfficialMT22** [comment]
found it... thanks. I need one more last help finding code. Its the cat Icons. --- fa-folder and fa-folder-open. 

trying to find this {{ downloads.CAT_ICON }}

**Comment by oxpus** [comment]
/ext/oxpus/dlext/controller/index.php
