### ISSUE TITLE
This download section has no categories

### ISSUE THREAD

**Issue by Sajaki** [oxpus/Download-32-Extension#27]
hi,

registered users can't download anything. 

Steps to reproduce: 
* click on download link https://www.avathar.be/forum/app.php/dlext/index 
* they get this warning :  "This download section has no categories". 

i can reproduce the issue when for any user taking over the user's permission.

* phpbb 3.3.1 
* download extension 8.1.10

**Comment by oxpus** [comment]
Have you updated the extension to 8.1.10 from a prior release?
At first please purge the forum cache and retry.
After this check the usergroup permissions of the categories.
At least one category should have the right permission to be viewed for all user or usergroups.
Another point is to check the extension banlist. Maybe this contains a dataset with the user id "0" or an "empty" ip adresse.
Delete this and retry.
You can check the permissions of each user with the extension permission check module in the ACP.
Have you used this to check out the user permissions to fix possible wrong settings?

Without more informations about your settings I cannot really help.

**Comment by Sajaki** [comment]
> At first please purge the forum cache and retry.

did that

> After this check the usergroup permissions of the categories.
> At least one category should have the right permission to be viewed for all user or usergroups.

did that. they seem correct. I deleted all permissions and set them again. 

> Another point is to check the extension banlist. Maybe this contains a dataset with the user id "0" or an "empty" ip adresse.
> Delete this and retry.
no banlist was set up.

**Comment by oxpus** [comment]
Hm, strange, but maybe it just helped to post the message here to persuade the extension to work...
