### ISSUE TITLE
unable to expand "filename". It is in an unsupported format

### ISSUE THREAD

**Issue by Sajaki** [oxpus/Download-32-Extension#28]
hello, 

since recently, all downloads are broken.

- the file is downloading but the zipfile is "broken". i get a mac warning that "unable to expand "filename". It is in an unsupported format".  
- when i upload a new file i get the same issue. 

what is working: 
- the hashed file on the server example (dlj9cucm4phdid7q_a5d70ff7ce0f8aec6e24c220031f7101.zip) is OK, when i download it via filezilla it is OK, expands normally. 
- workaround : What i have done is to change the download into "external url" and this is still working. 
- the issue does not appear on localhost.

i'm using v8.2.3, phpBB 3.3.3 and php 7.4.16

on php 8.0.3 i get php errors in the ACP when uploading new files.

**Comment by oxpus** [comment]
First: The extension is not yet testet and build for php 8! So I'll not support this combination at the moment.

And to the error in the downloads:
Did you clear the forum cache? Ideally, the entire folder "production " in the folder /cache/.
Do the downloaded files have the correct file sizes or are they downloaded with a significantly smaller file volume?
How big are the files for the download? Is it possible that something is wrong with the server settings, especially that the downloads are working on the local computer?

**Comment by oxpus** [comment]
The extension ist not yet testet under php 8, so there's currently no support for this combination.

How big are the files after the download? Are they the correct size as they have on the server?
Can it be that something does not fit in the server settings, e.g. the permissions of the folders for the downloads, in particular that the extension on the local computer seems to work?

**Comment by oxpus** [comment]
`on php 8.0.3 i get php errors in the ACP when uploading new files.`

What is the error message?
I have just uploaded a download myself under PHP 8 with the extension via the ACP module and received no error.

**Comment by Sajaki** [comment]
I think i messed up when restoring my site using filezilla, it transfers all files without extension as ascii instead of binary by default unless a checkbox is unset in the settings. so now all files in /files/dlext/downloads without extension are broken.
