### ISSUE TITLE
Two commits never submitted

### ISSUE THREAD

**Issue by Galixte** [oxpus/Download-32-Extension#3]
Hi @oxpus,

did you see these commits made by @Sajaki? I think he never submitted them to you:

- https://github.com/Sajaki/Download-32-Extension/commit/1cfb0453379339308ecf86162c840716d23556af
- https://github.com/Sajaki/Download-32-Extension/commit/06ddaeba26b473fd6d934745adf78be68151820d

Regards.

**Comment by oxpus** [comment]
No, these commits are new for me.
I leave them unmerged until they will be requested.

**Comment by Galixte** [comment]
- https://github.com/Sajaki/Download-32-Extension/commit/1cfb0453379339308ecf86162c840716d23556af has been already submitted: https://phpbb3.oxpus.net/viewtopic.php?f=15&t=743, so it’s ok.
-  https://github.com/Sajaki/Download-32-Extension/commit/06ddaeba26b473fd6d934745adf78be68151820d adds the support for the style PBWoW 3: https://www.phpbb.com/customise/db/style/pbwow3/.
