### ISSUE TITLE
[phpBB Debug] PHP Warning: in file [ROOT]/ext/oxpus/dlext/phpbb/classes/class_dl_init.php on line 281: sizeof(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Galixte** [oxpus/Download-32-Extension#8]
Hi @oxpus,

on my board a user reported to me this warning: `[phpBB Debug] PHP Warning: in file [ROOT]/ext/oxpus/dlext/phpbb/classes/class_dl_init.php on line 281: sizeof(): Parameter must be an array or an object that implements Countable`.

This line: https://github.com/oxpus/Download-32-Extension/blob/master/oxpus/dlext/phpbb/classes/class_dl_init.php#L281. What should we replace `sizeof()` with? `count()`?

His board is phpBB 3.2.7 with PHP 7.2.18.

**Comment by oxpus** [comment]
Fixed with commit #61: https://github.com/oxpus/Download-32-Extension/commit/4cc417dc873f1129514168b39783a62229e04c31

**Comment by Galixte** [comment]
Thanks!
